# name: Deploy project to our server

# on:
#   push:
#     branches:
#       - main

# jobs:
#   ftp-deploy:
#     name: FTP Deploy
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 2

#       - name: Deploy via FTP
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
#         with:
#           server: ftp.thewarriors.team
#           username: milesbanks@milesbanks.thewarriors.team
#           password: "=r{+5gX_#@&5wsNf"
